version: '3.9'

services:

  usuarios:
    build:
      context: ./microservicio-usuarios/microservicio-usuarios
    container_name: ms-usuarios
    ports:
      - "8081:8081"

  productos:
    build:
      context: ./microservicio-productos/microservicio-productos
    container_name: ms-productos
    ports:
      - "8082:8082"

  frontend:
    build:
      context: ./tienda-online
    container_name: tienda-online
    ports:
      - "4200:80"
    depends_on:
      - usuarios
      - productos